# Generated by Django 4.2.6 on 2023-10-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
