# Generated by Django 4.2.6 on 2023-10-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_remove_customuser_is_health_worker_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='accepted',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
